name: Generate Cool Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate Snake with Custom Design
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=0d1117,161b22,2a0a45,00ff87,00ffd5&cell_radius=4&cell_size=14&duration_seconds=10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Glow Effect to Snake
        run: |
          # Add SVG filter definition
          sed -i 's|<svg |<defs><filter id="glow"><feGaussianBlur stdDeviation="3" result="coloredBlur"/><feMerge><feMergeNode in="coloredBlur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><svg |' dist/github-contribution-grid-snake-dark.svg
          
          # Apply filter to snake path
          sed -i 's/<path d="M/<path filter="url(#glow)" d="M/g' dist/github-contribution-grid-snake-dark.svg
          
          # Add background gradient
          sed -i 's|<svg |<linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color:#2a0a45;stop-opacity:1" /><stop offset="100%" style="stop-color:#000000;stop-opacity:1" /></linearGradient><rect width="100%" height="100%" fill="url(#grad1)" />|' dist/github-contribution-grid-snake-dark.svg

      - name: Deploy Snake Animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}