name: Generate Enhanced Contribution Snake Animation

on:
  # Run every 12 hours
  schedule:
    - cron: "0 */12 * * *" 
  # Manual trigger
  workflow_dispatch:
  # Run on push to main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Generate enhanced snake animations from your GitHub contributions graph
      - name: Generate Enhanced GitHub Contribution Snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=default&snakeColor=%2300ff7f&cellSize=12&animationSpeed=1.2&strokeWidth=2
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&snakeColor=%23ff4500&cellSize=12&animationSpeed=1.2&strokeWidth=2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Deploy the generated SVGs to the output branch (and optionally GitHub Pages)
      - name: Push GitHub Contribution Snake SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
